---
title: "XGboost"
output: html_notebook
---

```{r}
##########################
######## XGBoost #########
##########################

# Load libraries
library(xgboost)
library(caret)
library(dplyr)
library(e1071)

# Use HOG features
feature_hog<-read.csv("hog.csv",header = T, as.is = T)
label<-read.csv("label_train.csv",header = T,as.is = T)
dat<-cbind(label[,2],feature_hog[,-1])
colnames(dat)[1]<-"label"

# Train and test split
train_index<-sample(1:nrow(dat),0.7*nrow(dat))

xgb_variables<-as.matrix(dat[,-1]) # Full dataset
xgb_label<-dat[,1] # Full label

# Split train data
xgb_train<-xgb_variables[train_index,]
train_label<-xgb_label[train_index]
train_matrix<-xgb.DMatrix(data = xgb_train, label=train_label)

# Split test data
xgb_test<-xgb_variables[-train_index,]
test_label<-xgb_label[-train_index]
test_matrix<-xgb.DMatrix(data = xgb_test, label=test_label)


## K-folds cross-validation to estimate error
num_of_classes<-length(unique(dat$label))
xgb_params<-list("objective"="multi:softprob",
                 "eval_metric"="mlogloss",
                 "num_class"=num_of_classes)
nround<-50 # number of xgboost rounds
cv.nfold<-5

xgb_cv_model<-xgb.cv(params = xgb_params,
                     data = train_matrix,
                     nrounds = nround,
                     nfold = cv.nfold,
                     verbose = F,
                     prediction = T)


## Out of fold prediction err
OOF_pred<-data.frame(xgb_cv_model$pred) %>%
  mutate(max_prob=max.col(.,ties.method = "last"),
         label=train_label+1)
head(OOF_pred)


## Confusion matrix
confusionMatrix(factor(OOF_pred$label),factor(OOF_pred$max_prob),mode = "everything")
```


```{r}
best_model<-xgb.train(params = xgb_params,
                      data = train_matrix,
                      nrounds = nround)

test_pred<-predict(best_model,newdata=test_matrix)
test_prediction<-matrix(test_pred,nrow = num_of_classes,ncol = length(test_pred)/num_of_classes) %>%
  t() %>%
  data.frame() %>%
  mutate(label=test_label+1,max_prob=max.col(.,"last"))

## confusion matrix of test set
confusionMatrix(factor(test_prediction$label),factor(test_prediction$max_prob),mode = "everything")

```

```{r}
### Use SIFT features
feature_sift<-read.csv("sift_train.csv",header = T, as.is = T)
label<-read.csv("label_train.csv",header = T,as.is = T)
dat<-cbind(label[,2],feature_sift[,-1])
colnames(dat)[1]<-"label"


# Train and test split
train_index<-sample(1:nrow(dat),0.7*nrow(dat))

xgb_variables<-as.matrix(dat[,-1]) # Full dataset
xgb_label<-dat[,1] # Full label

# Split train data
xgb_train<-xgb_variables[train_index,]
train_label<-xgb_label[train_index]
train_matrix<-xgb.DMatrix(data = xgb_train, label=train_label)

# Split test data
xgb_test<-xgb_variables[-train_index,]
test_label<-xgb_label[-train_index]
test_matrix<-xgb.DMatrix(data = xgb_test, label=test_label)


## K-folds cross-validation to estimate error
num_of_classes<-length(unique(dat$label))
xgb_params<-list("objective"="multi:softprob",
                 "eval_metric"="mlogloss",
                 "num_class"=num_of_classes)
nround<-50 # number of xgboost rounds
cv.nfold<-5

xgb_cv_model<-xgb.cv(params = xgb_params,
                     data = train_matrix,
                     nrounds = nround,
                     nfold = cv.nfold,
                     verbose = F,
                     prediction = T)


## Out of fold prediction err
OOF_pred<-data.frame(xgb_cv_model$pred) %>%
  mutate(max_prob=max.col(.,ties.method = "last"),
         label=train_label+1)
head(OOF_pred)


## Confusion matrix
confusionMatrix(factor(OOF_pred$label),factor(OOF_pred$max_prob),mode = "everything")

```

```{r}
best_model<-xgb.train(params = xgb_params,
                      data = train_matrix,
                      nrounds = nround)

test_pred<-predict(best_model,newdata=test_matrix)
test_prediction<-matrix(test_pred,nrow = num_of_classes,ncol = length(test_pred)/num_of_classes) %>%
  t() %>%
  data.frame() %>%
  mutate(label=test_label+1,max_prob=max.col(.,"last"))

## confusion matrix of test set
confusionMatrix(factor(test_prediction$label),factor(test_prediction$max_prob),mode = "everything")
```

